import type { StrategyConfig } from './types.js';

export const STRATEGIES: StrategyConfig[] = [
  {
    id: 'early-edge',
    name: 'Early Edge',
    mode: 'early-edge',
    minEdge: 0.06,
    maxTimeToResolution: 120,
    minTimeToResolution: 20,
    requireSpreadConfirm: true,
    sizeInDollars: 5,
  },
  {
    id: 'no-trade-zone',
    name: 'No-Trade Zone',
    mode: 'no-trade-zone',
    minEdge: 0.06,
    maxTimeToResolution: 120,
    minTimeToResolution: 20,
    requireSpreadConfirm: true,
    sizeInDollars: 5,
  },
  {
    id: 'window-phase',
    name: 'Window Phase',
    mode: 'window-phase',
    minEdge: 0.05,
    maxTimeToResolution: 180,
    minTimeToResolution: 20,
    requireSpreadConfirm: true,
    sizeInDollars: 5,
  },
  {
    id: 'consensus',
    name: 'Consensus Score',
    mode: 'consensus',
    minEdge: 0.05,
    maxTimeToResolution: 120,
    minTimeToResolution: 15,
    requireSpreadConfirm: true,
    sizeInDollars: 5,
  },
  {
    id: 'agreement',
    name: 'Agreement',
    mode: 'agreement',
    minEdge: 0.05,
    maxTimeToResolution: 120,
    minTimeToResolution: 15,
    requireSpreadConfirm: true,
    sizeInDollars: 5,
  },
];
